name: style_mongo
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com
publish_to: none
environment:
  sdk: '>=2.14.0 <3.0.0'


dependencies:
  mongo_dart: ^0.7.2

  style_dart:
    path: ../../style/packages/style
#   path: ^1.8.0

dev_dependencies:
  style_test:
    path: ../../style/packages/style_test
  lints: ^1.0.0
  test: ^1.16.0
