name: style_mongo
description: MongoDb DataAccess implementation for style_dart.
version: 1.0.0
# homepage: https://www.example.com
publish_to: none
environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  mongo_dart: ^0.7.4
  style_dart: ^1.0.2+5

dev_dependencies:
  style_test: ^1.0.0+2
  lints: ^1.0.1
  test: ^1.19.4
