name: style_mongo
description: MongoDb DataAccess implementation for style_dart.
version: 1.0.0+1
homepage: https://github.com/Mehmetyaz/style_mongo
repository: https://github.com/Mehmetyaz/style_mongo

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  mongo_dart: ^0.7.4+1
  style_dart: ^1.0.2+8

dev_dependencies:
  style_test: ^1.0.0+3
  lints: ^2.0.0
  test: ^1.21.1
